---
- digital_ocean: >
    state=present
    ssh_key_ids={{ default_key }}
    command=droplet
    name={{ item.name }}.local
    size_id={{ item.size|default(default_size) }}
    region_id={{ item.region|default(default_region) }}
    image_id={{ item.image|default(default_image) }}
    wait_timeout=500
    unique_name=true
  register: instances
  with_items: droplets
- debug: var=instances.results
- dnsimple: >
    state=present
    domain=secure-pipeline.com
    record={{ item.item.name }}
    type=A
    ttl=3600
    value={{ item.droplet.ip_address }}
  with_items: instances.results
